name: Update README with Todoist

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Todoist Readme action
      - name: Update README with Todoist stats
        uses: abhisheknaiidu/todoist-readme@master
        env:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}

      # Step 3: Push changes to GitHub using a PAT
      - name: Commit and push changes
        run: |
          git config --global user.email "eugyneehunter@gmail.com"
          git config --global user.name "Grealishgit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "📈 Update README with Todoist stats" || echo "No changes to commit"
          git push
